### ISSUE TITLE
Jon Site QA

### ISSUE THREAD

**Issue by johnrom** [johnrom/johnny-site-review#1]
## Desktop / All sizes

The desktop experience is pretty much perfect with few imperfections. The columns on project pages work very well and look sleek.

- [ ] Link Broken:
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/c8b789a7-b891-4e99-bfff-91f2c670a516)
- [ ] Link Broken:
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/7ba706f8-06ab-4172-a46e-939d6f1a4e3c)
- [ ] Missing whitespace:
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/69601738-0c84-4b15-af39-6f4df8ecf647)
- [ ] Years misaligned:
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/6f158539-6a35-45e4-980a-b0400f0ef5e9)
- [ ] Design consideration: custom scrollbar is a nice touch, but over dark theme it becomes invisible and is an accessibility issue:
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/79343a1d-8e82-4e77-90db-705c1ec2a00f)

## Mobile

The mobile version is a little less polished, which could be fine if you expect most viewers to be on desktop. However, someone designing websites should be primarily considering the mobile form factor for a website (some of our websites have less than 10% desktop usage). Therefore, I'd expect a hiring manager for a web design / ux team to check the mobile side and evaluate your chops there, with bonus points if it is polished.

> ℹ️ Nobody cares about tablets.

- [ ] Mobile nav appears empty. Maybe put the projects here as well, or make Download my Resume more centered to make it appear less empty.
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/3474c7c0-d6d0-474f-9810-69d867d61fe9)
- [ ] Header hierarchy of the home page footer don't make quite as much sense on mobile. Work Experience, Certifications etc might need more impact:
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/5731c448-6339-4718-b9fc-f40a430a4b13)
- [ ] Can these buttons be side-by-side?
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/94e0cbbd-08f4-4c54-aa89-a96a65a7da00)
- [ ] Centered text on mobile is a little dated on project pages
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/8f00eda3-bc64-4e7e-beef-b926c63b51cf)
- [ ] This text alignment feels off, or like it should be a blockquote with a line down the left side:
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/8860a7a7-dcde-4cae-98a4-05ae8de0b3d9)
- [ ] Unlike desktop, a lot of the project images feel like run-on sentences on mobile. They could use spacing / some sort of bounding box to make the beginning, end, and focus of images clear. Bonus points for caption text because it's hard to identify what the images are supposed to be. Triple bonus points if you can turn some of the longer series' of images into a slider with arrows / swiping left and right with captions.
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/0d6c75cb-fcf9-4a39-807c-21e3d54fe934)
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/547417c2-2618-4c94-a0e6-f30a0d09f1a3)
- [ ] Double video on Foundational Planning:
  > ![image](https://github.com/johnrom/johnny-site-review/assets/1881482/69a44bdf-a129-4b2e-ae88-6929ad41e7d7)

**Comment by jprussel** [comment]
> ## Desktop / All sizes
> The desktop experience is pretty much perfect with few imperfections. The columns on project pages work very well and look sleek.
> 
> * [x]  Link Broken:
> Broken link fixed.
> * [x]  Link Broken:
>   Broken link fixed.
> * [x]  Missing whitespace:
>   Whitespace fixed.
> * [x]  Years misaligned:
>  Whitespace added between paragraphs so hopefully it doesn't collapse on some browsers.
> * [ ]  Design consideration: custom scrollbar is a nice touch, but over dark theme it becomes invisible and is an accessibility issue:
>   That's your browser doing that, there's no scrollbar CSS.
> 
> ## Mobile
> The mobile version is a little less polished, which could be fine if you expect most viewers to be on desktop. However, someone designing websites should be primarily considering the mobile form factor for a website (some of our websites have less than 10% desktop usage). Therefore, I'd expect a hiring manager for a web design / ux team to check the mobile side and evaluate your chops there, with bonus points if it is polished.
> 
> > ℹ️ Nobody cares about tablets.
> 
> * [ ]  Mobile nav appears empty. Maybe put the projects here as well, or make Download my Resume more centered to make it appear less empty.
>  May be able to fix with custom CSS but unfortunately that's a Squarespace thing. I wanted to get rid of it entirely but couldn't figure out how without custom CSS.
> * [x]  Header hierarchy of the home page footer don't make quite as much sense on mobile. Work Experience, Certifications etc might need more impact:
>   Added more contrast.
> * [x]  Can these buttons be side-by-side?
>   Made them full width instead. I thought they looked better that way.
> * [ ]  Centered text on mobile is a little dated on project pages
>  Not possible to change without custom CSS.
> * [x]  This text alignment feels off, or like it should be a blockquote with a line down the left side:
>   Should be fixed now.
> * [x]  Unlike desktop, a lot of the project images feel like run-on sentences on mobile. They could use spacing / some sort of bounding box to make the beginning, end, and focus of images clear. Bonus points for caption text because it's hard to identify what the images are supposed to be. Triple bonus points if you can turn some of the longer series' of images into a slider with arrows / swiping left and right with captions.
> Fixed spacing issues with images. They should have room between them now.
> * [x]  Double video on Foundational Planning:
>   Squarespace deleted all my videos when I upgraded the site (thanks!) Added them back.

**Comment by johnrom** [comment]
> That's your browser doing that, there's no scrollbar CSS.

Weird! Yeah my work PC doesn't have that issue. :shrug:

Changes are approved 😁
